# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$tsvmmyr.PVGiNlRbQf1RE.NcpqhZa9MTOObyrOdVfglYS/RJQRJEW
                        roles: 'ROLE_ADMIN'
                    other:
                        password: $2y$13$mYi5OMjBfIrQ0NGkT9odxeW/5KAyrGb0qRC/O/A1TEpRvqnCiu4qC


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: in_memory
            form_login:
                login_path: login
                check_path: login
            logout: true
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - {path: ^/admin, role: ROLE_ADMIN}
        - {path: ^/productos, role: ROLE_ADMIN}
        - {path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY}